[tool.poetry]
name = "aw-server"
version = "0.10"
description = ""
authors = ["Erik Bj√§reholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.scripts]
aw-server = "aw_server:main"

[tool.poetry.dependencies]
python = "^3.6"
aw-core = {git = "https://github.com/ActivityWatch/aw-core.git"}
aw-client = {git = "https://github.com/ActivityWatch/aw-client.git"}
appdirs = "^1.4.3"
flask = "^1.1.1"
flask-restx = "^0.2.0"
flask-cors = "^3.0.8"

[tool.poetry.dev-dependencies]
mypy = "*"
pytest = "^6.0"
pytest-flask = "^0.15.0"
pytest-benchmark = "^3.2.2"
pytest-cov = "^2.10.1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov-report=term --cov-report=xml --cov-report=html --cov=aw_server"
python_files = ["*.py",]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
