[tool.poetry]
name = "aw-server"
version = "0.9"
description = ""
authors = ["Erik Bj√§reholt <erik@bjareho.lt>"]
license = "MPL-2.0"

[tool.poetry.scripts]
aw-server = "aw_server:main"

[tool.poetry.dependencies]
python = "^3.6"
aw-core = {git = "https://github.com/ActivityWatch/aw-core.git"}
aw-client = {git = "https://github.com/ActivityWatch/aw-client.git"}
appdirs = "^1.4.3"
flask = "^1.1.1"
flask-restx = "^0.1.1"
flask-cors = "^3.0.8"
werkzeug = "<1.0.0"  # 1.0.0 kept back due to bug in flask-restx, see: https://github.com/ActivityWatch/activitywatch/issues/346

[tool.poetry.dev-dependencies]
mypy = "^0.761"
pytest = "^5.3.2"
pytest-flask = "^0.15.0"
pytest-benchmark = "^3.2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
